apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany # Not available for hostPath
    # - ReadWriteMany # Not available for hostPath
  hostPath:
    path: /data/story
    type: DirectoryOrCreate # Directory, DirectoryOrCreate
