apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  type: LoadBalancer
  selector:
    app: second-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 # target port inside of container
    # - protocol: "TCP"
    #   port: 443
    #   targetPort: 443
