POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indpc251cHJzakBnbWFpbC5jb20iLCJleHAiOjE3MDM0MDY0NTEsInVzZXJJZCI6MX0.yfjDPZyXRAWhKIrBcMul-t7wDDg3Oj_RYMKvg84A38s

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}