PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Test event",
    "description": "A test event 2",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}