apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql/mysql-server:8.0.23
      env:
        - name: MYSQL_ROOT_PASSWORD
          value:
        - name: MYSQL_DATABASE
          value: 

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  type: ClusterIP
