# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp
#   labels:
#     app: webapp
#     release: "0"
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0-arm64
#
# ---
# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: webapp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: webapp
#   template: # template for the pod
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#       - name: webapp
#         image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-arm64
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template: # template for the pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-arm64

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release2-arm64


#mysql/mysql-server:8.0.23
