apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-fontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-frontend
  template:
    metadata:
      labels:
        app: tasks-frontend
    spec:
      containers:
        - name: tasks-frontend
          image: wisnuprsj/kub-networks-frontend:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
